package apis

import "github.com/operator-framework/operator-sdk/pkg/status"

// EnforcingReconcileStatus represent the status of the last reconcile cycle. It's used to communicate success or failer and the error message
// +k8s:openapi-gen=true
type EnforcingReconcileStatus struct {

	// ReconcileStatus this is the general status of the main reconciler
	Conditions status.Conditions `json:"conditions"`

	//LockedResourceStatuses containes the reconcile status for each of the managed resoureces
	LockedResourceStatuses map[string]status.Conditions `json:"lockedResourceStatuses,omitempty"`
}

// EnforcingReconcileStatusAware represnt a CRD type that has been enabled with ReconcileStatus, it can then benefit of a series of utility methods.
type EnforcingReconcileStatusAware interface {
	GetEnforcingReconcileStatus() EnforcingReconcileStatus
	SetEnforcingReconcileStatus(enforcingReconcileStatus EnforcingReconcileStatus)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcingReconcileStatus) DeepCopyInto(out *EnforcingReconcileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(status.Conditions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.LockedResourceStatuses != nil {
		in, out := &in.LockedResourceStatuses, &out.LockedResourceStatuses
		*out = make(map[string]status.Conditions, len(*in))
		for key, val := range *in {
			var outVal map[status.ConditionType]status.Condition
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(status.Conditions, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcingReconcileStatus.
func (in *EnforcingReconcileStatus) DeepCopy() *EnforcingReconcileStatus {
	if in == nil {
		return nil
	}
	out := new(EnforcingReconcileStatus)
	in.DeepCopyInto(out)
	return out
}
